### ISSUE TITLE
Finetuning on GL3D

### ISSUE THREAD

**Issue by Smellly** [zju3dv/GIFT#3]
Could you share the yaml file about finetuning on the GL3D datasets ?
I can't reproduce the pretrained model results on relative pose error in the paper.
Thank you.

**Comment by liuyuan-pal** [comment]
Hi~Since the code for training on the dataset GL3D need to be further reorganized, we do not provide the training code for it. 
But recently, we are working on testing the GIFT on the IMW challenge (https://vision.uvic.ca/image-matching-challenge), so we plan to release the model used in this challenge.
