### ISSUE TITLE
How about the accuracy of GIFT  at a larger scale ratio of image pair ?

### ISSUE THREAD

**Issue by xiaoguang12** [zju3dv/GIFT#7]
Hi thanks for your outstanding work, i wonder How about the accuracy of GIFT  at a **larger scale ratio** of image pair such ac scale ratio of  or even larger. in your paper you seem just test at 2^1.5.  thanks  looking forward to your reply.

Best wish
                                                                                                                                                                            xiaoguang

**Comment by xiaoguang12** [comment]
scale ratio of 10 or even more

**Comment by liuyuan-pal** [comment]
We didn't do systematical experiments to test it under a large scale ratio like this, because it's relatively rare in matching natural images.
Theoretically, if sampling more elements on the scale axis (currently only 5 elements), then the invariance of GIFT to scale will be stronger. 
But, meanwhile, sampling more elements means more computational complexity.

**Comment by xiaoguang12** [comment]
Ok i see  thanks for your reply.
